### ISSUE TITLE
crash when send

### ISSUE THREAD

**Issue by zhj4478** [emersion/go-smtp-server#1]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x40ffe55]

goroutine 8 [running]:
panic(0x458e160, 0xc82000a0d0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/ProtonMail/Desktop-Bridge/vendor/github.com/emersion/go-smtp-server.(*Conn).mailHandler(0xc8200144e0, 0xc82011c570, 0x4, 0xc82011c575, 0x1c)
	/Users/Yanfeng/.go/src/github.com/ProtonMail/Desktop-Bridge/vendor/github.com/emersion/go-smtp-server/conn.go:201 +0x545
github.com/ProtonMail/Desktop-Bridge/vendor/github.com/emersion/go-smtp-server.(*Conn).handle(0xc8200144e0, 0xc82011c570, 0x4, 0xc82011c575, 0x1c)
	/Users/Yanfeng/.go/src/github.com/ProtonMail/Desktop-Bridge/vendor/github.com/emersion/go-smtp-server/conn.go:65 +0x968
github.com/ProtonMail/Desktop-Bridge/vendor/github.com/emersion/go-smtp-server.(*Server).handleConn(0xc820100500, 0xc8200144e0, 0x0, 0x0)
	/Users/Yanfeng/.go/src/github.com/ProtonMail/Desktop-Bridge/vendor/github.com/emersion/go-smtp-server/server.go:64 +0x1bb
created by github.com/ProtonMail/Desktop-Bridge/vendor/github.com/emersion/go-smtp-server.(*Server).Listen
	/Users/Yanfeng/.go/src/github.com/ProtonMail/Desktop-Bridge/vendor/github.com/emersion/go-smtp-server/server.go:38 +0xcf
exit status 2
```

**Comment by emersion** [comment]
Fixed in a90b46d0d9c095f828fdd112e8efd4c3fe38e7b2.
